
server:
  port: 7777

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  #datasource:
  #  url: jdbc:oracle:thin:@localhost:1521/xe
  #  username: eddi
  #  password: eddi123
  #  driver-class-name: oracle.jdbc.OracleDriver
  #  dialect: org.hibernate.dialect.Oracle10gDialect